apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 036068869120.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
  imagePullSecrets:
  - name: ecr-secret
